# Generated by Django 4.0.5 on 2022-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name')),
                ('customer_address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Customer Address')),
                ('customer_pri_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Customer Pri_Phone')),
                ('customer_sec_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Customer Sec_Phone')),
                ('customer_dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('customer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('customer_status', models.CharField(choices=[('NEW', 'New'), ('REPEAT', 'Repeat'), ('DORMANT', 'Dormant'), ('BLACK-LISTED', 'In Black List')], default='NEW', max_length=20, verbose_name='Customer Status')),
                ('customer_notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer Notes')),
                ('customer_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Customer Rating')),
            ],
        ),
    ]
