# Generated by Django 4.0.5 on 2022-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Crop Name')),
                ('crop_type', models.CharField(choices=[('Fo', 'Food Crop'), ('Fe', 'Feed Crop'), ('Fi', 'Fiber Crop'), ('Oi', 'Oil Crop'), ('Or', 'Ornamental Crop'), ('In', 'Industrial Crop')], default='Fo', max_length=2, verbose_name='Crop Type')),
                ('crop_rate_in_market', models.CharField(blank=True, max_length=15, null=True, verbose_name='Crop Rate In Market')),
                ('crop_cost_to_grow', models.CharField(blank=True, max_length=14, null=True, verbose_name='Crop Cost To Grow')),
                ('crop_seeds_per_acre', models.CharField(blank=True, max_length=14, null=True, verbose_name='Crop Seeds Per Acre')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_pri_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Customer Primary Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_sec_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Customer Secondary Phone'),
        ),
    ]
