# Generated by Django 4.0.5 on 2022-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0003_crop_alter_customer_customer_pri_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='crop_rate_in_market',
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_average_rate_in_market',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Crop Average Rate In Market'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Crop Description'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_diseases',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Crop Diseases'),
        ),
    ]
