# Generated by Django 4.0.5 on 2022-06-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0004_remove_crop_crop_rate_in_market_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipment Name')),
                ('equipment_type', models.CharField(blank=True, max_length=2, null=True, verbose_name='equipments type of equipments')),
                ('equipment_cost', models.CharField(blank=True, max_length=13, null=True, verbose_name='equipments cost')),
                ('equipment_life_time', models.CharField(blank=True, max_length=13, null=True, verbose_name='Lifetime Of Equipments')),
            ],
        ),
        migrations.CreateModel(
            name='Inorganic_Fertilizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fertilizer Name')),
                ('fertilizer_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='Fertilizer Cost')),
                ('fertilizer_methods_to_use', models.CharField(blank=True, max_length=300, null=True, verbose_name='Methods to Use')),
                ('fertilizer_type', models.CharField(blank=True, max_length=13, null=True, verbose_name='Fertilizers  Types')),
            ],
        ),
        migrations.CreateModel(
            name='Labourer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labourer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Labourer Name')),
                ('labourer_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Labourer Phone')),
                ('labourer_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('labourer_taluk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taluk')),
                ('labourer_district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('labourer_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('labourer_Specialize_in_certain_work', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specialize in Certain Work')),
                ('labourer_availability', models.CharField(blank=True, max_length=50, null=True, verbose_name='Labourer Availability')),
            ],
        ),
        migrations.CreateModel(
            name='Lands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('Ar', 'Arable Crop Land'), ('Pr', 'Permanent Crop Land'), ('Pe', 'Permanent Grassland')], default='Ar', max_length=2, verbose_name='Land Type')),
                ('land_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Land Description')),
                ('land_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Land Details')),
                ('land_suitable_crop_details', models.CharField(blank=True, max_length=120, null=True, verbose_name='Crop Suitable Land Details')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticides_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pesticides name')),
                ('pesticides_cost', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pesticides Cost')),
                ('pesticides_methods_to_use', models.CharField(blank=True, max_length=300, null=True, verbose_name='Methods to Use')),
            ],
        ),
        migrations.CreateModel(
            name='Seeds_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('vendor_email_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id')),
                ('vendor_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('vendor_taluk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taluk')),
                ('vendor_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('vendor_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('vendor_shop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shop Name')),
                ('vendor_availability', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Availability')),
                ('vendor_review', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Review')),
                ('vendor_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Vendor Rating')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_pincode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_taluk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taluk'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_village',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Village'),
        ),
        migrations.CreateModel(
            name='Pesticides_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('vendor_email_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id')),
                ('vendor_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('vendor_taluk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taluk')),
                ('vendor_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('vendor_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('vendor_shop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shop Name')),
                ('vendor_availability', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Availability')),
                ('vendor_review', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Review')),
                ('vendor_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Vendor Rating')),
                ('pesticides_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.pesticides', verbose_name='Pesticides Name')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('vendor_email_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id')),
                ('vendor_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('vendor_taluk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taluk')),
                ('vendor_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('vendor_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('vendor_shop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shop Name')),
                ('vendor_availability', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Availability')),
                ('vendor_review', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Review')),
                ('vendor_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Vendors Rating')),
                ('equipment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.equipment', verbose_name='Equipment Name')),
            ],
        ),
    ]
