# Generated by Django 4.0.5 on 2022-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0005_equipment_inorganic_fertilizers_labourer_lands_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lands',
            new_name='Land',
        ),
    ]
