# Generated by Django 4.0.5 on 2022-06-09 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0006_rename_lands_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seed Name')),
                ('seed_type', models.CharField(choices=[('Wh', 'Wheat'), ('Ma', 'Maize'), ('Pa', 'Paddy'), ('Gr', 'Groundnut'), ('Pe', 'Pearl Millet'), ('Ba', 'Barley'), ('So', 'Soybean'), ('Mu', 'Mung Bean'), ('Ps', 'Peas'), ('Vi', 'Vigna Mungo'), ('Su', 'Sunflower'), ('Sr', 'Sorghum'), ('Co', 'Cowpea'), ('Ra', 'Ragi'), ('Jo', 'Jowar'), ('Li', 'Linseed'), ('Mi', 'Millets'), ('Le', 'Lentil'), ('Ar', 'Araikeerai Seed')], default='Wh', max_length=2, verbose_name='Seed Type')),
                ('seed_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Seed Description')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Tr', 'Tractor'), ('Co', 'Combine Harvester'), ('Pl', 'Plough'), ('Sp', 'Sprayer'), ('Cu', 'Cultivator'), ('Ir', 'Irrigation'), ('Ha', 'Harrow'), ('Ba', 'Baler'), ('Se', 'Seed Drill'), ('Di', 'Disc Harrow'), ('Br', 'Broadcast Spreader'), ('Ra', 'Rake'), ('Ma', 'Manure spreader'), ('Ro', 'Rotary Tiller'), ('Pt', 'Plant'), ('Sd', 'Seed'), ('We', 'Weeder'), ('Bc', 'Backhoe'), ('Pe', 'Power Tiller'), ('Ps', 'Paper Shredder'), ('Tm', 'Threshing Machine'), ('Cu', 'Cultipacker'), ('Lo', 'Loader'), ('Sh', 'Shovel')], default='Tr', max_length=2, verbose_name='equipments type of equipments'),
        ),
        migrations.AddField(
            model_name='seeds_vendor',
            name='seed_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.seed', verbose_name='Seed Name'),
        ),
    ]
