# Generated by Django 4.0.5 on 2022-06-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0007_seed_alter_equipment_equipment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_type', models.CharField(choices=[('Su', 'Summer Season'), ('Wi', 'Winter Season'), ('Au', 'Autumn Season'), ('Sp', 'Spring season'), ('Dr', 'Dry Season'), ('At', 'Atlantic Hurricane Season')], default='Su', max_length=2, verbose_name='Season Type')),
                ('season_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Season Description')),
                ('season_suitable_crop_details', models.CharField(blank=True, max_length=50, null=True, verbose_name='Crop Suitable Season Details')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_cost',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Equipment cost'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_life_time',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Lifetime Of Equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Tr', 'Tractor'), ('Co', 'Combine Harvester'), ('Pl', 'Plough'), ('Sp', 'Sprayer'), ('Cu', 'Cultivator'), ('Ir', 'Irrigation'), ('Ha', 'Harrow'), ('Ba', 'Baler'), ('Se', 'Seed Drill'), ('Di', 'Disc Harrow'), ('Br', 'Broadcast Spreader'), ('Ra', 'Rake'), ('Ma', 'Manure spreader'), ('Ro', 'Rotary Tiller'), ('Pt', 'Plant'), ('Sd', 'Seed'), ('We', 'Weeder'), ('Bc', 'Backhoe'), ('Pe', 'Power Tiller'), ('Ps', 'Paper Shredder'), ('Tm', 'Threshing Machine'), ('Cu', 'Cultipacker'), ('Lo', 'Loader'), ('Sh', 'Shovel')], default='Tr', max_length=2, verbose_name='Type of Equipment'),
        ),
        migrations.CreateModel(
            name='Inorganic_Fertlizer_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('vendor_email_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id')),
                ('vendor_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('vendor_taluk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taluk')),
                ('vendor_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('vendor_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('vendor_shop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shop Name')),
                ('vendor_availability', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Availability')),
                ('vendor_review', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Review')),
                ('vendor_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Vendors Rating')),
                ('fertilizer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.inorganic_fertilizers', verbose_name='Fertilizer Name')),
            ],
        ),
        migrations.CreateModel(
            name='Farming_Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('So', 'Soil Preparation'), ('Sw', 'Sowing'), ('Ma', 'Manuring'), ('Ir', 'Irrigation'), ('We', 'Weeding'), ('Ha', 'Harvesting'), ('St', 'Storage')], default='So', max_length=2, verbose_name='Main Farming Methods  Type')),
                ('method_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Method Description')),
                ('crop_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.crop', verbose_name='Crop Name')),
            ],
        ),
    ]
