# Generated by Django 4.0.5 on 2022-06-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0008_season_alter_equipment_equipment_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organic_Fertilizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fertilizer Name')),
                ('fertilizer_type', models.CharField(choices=[('Ma', 'Manure'), ('Co', 'Compost'), ('Ro', 'Rock Phospate'), ('Ch', 'Chicken Litter'), ('Bo', 'Bone Meal'), ('Ve', 'Vermicompost')], default='Ma', max_length=2, verbose_name='Fertilizer Type')),
                ('fertilizer_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Fertilizer Description')),
                ('fertilizer_cost', models.CharField(blank=True, max_length=120, null=True, verbose_name='Fertilizer Cost')),
                ('fertilizer_methods_to_use', models.CharField(blank=True, max_length=300, null=True, verbose_name='Methods to Use')),
            ],
        ),
        migrations.CreateModel(
            name='Soil_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Test Name')),
                ('test_done', models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Test Done')),
                ('test_done_date', models.DateField(blank=True, null=True, verbose_name='Test Conducted Date')),
                ('test_result_date', models.DateField(blank=True, null=True, verbose_name='Test Result Date')),
                ('test_done_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Test Done By')),
            ],
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers',
            name='fertilizer_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Fertilizer Description'),
        ),
        migrations.AlterField(
            model_name='inorganic_fertilizers',
            name='fertilizer_type',
            field=models.CharField(choices=[('Ni', 'Nitrogen Fertilizers'), ('Ph', 'Phosphorous Fertilizers'), ('Po', 'Potassium Fertilizers'), ('Su', 'Sulfur,Calcium and Magnesium Fertilizers'), ('Mi', 'Micronutrient Fertilizers')], default='Ni', max_length=2, verbose_name='Fertilizer Type'),
        ),
        migrations.CreateModel(
            name='Seeds_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mapping Name')),
                ('seed_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.seed', verbose_name='Seed Name')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.seeds_vendor', verbose_name='Vendor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Season_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mapping Name')),
                ('crop_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.crop', verbose_name='Crop Name')),
                ('season_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.season', verbose_name='Season Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticides_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mapping Name')),
                ('pesticides_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.pesticides', verbose_name='Pesticides Name')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.pesticides_vendor', verbose_name='Vendor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Organic_Fertlizer_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Name')),
                ('vendor_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('vendor_email_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email Id')),
                ('vendor_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('vendor_taluk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taluk')),
                ('vendor_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('vendor_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('vendor_shop_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Shop Name')),
                ('vendor_availability', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Availability')),
                ('vendor_review', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor Review')),
                ('vendor_rating', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], default='5', max_length=1, verbose_name='Vendors Rating')),
                ('fertilizer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.organic_fertilizers', verbose_name='Fertilizer Name')),
            ],
        ),
        migrations.CreateModel(
            name='Organic_Fertilizers_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mapping Name')),
                ('fertilizer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.organic_fertilizers', verbose_name='Fertilizer Name')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.organic_fertlizer_vendor', verbose_name='Vendor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Inorganic_Fertilizers_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mapping Name')),
                ('fertilizer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.inorganic_fertilizers', verbose_name='Fertilizer Name')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.inorganic_fertlizer_vendor', verbose_name='Vendor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mapping Name')),
                ('equipment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.equipment', verbose_name='Equipment Name')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.equipment_vendor', verbose_name='Vendor Name')),
            ],
        ),
    ]
