# Generated by Django 4.0.5 on 2022-06-09 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0009_organic_fertilizers_soil_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='crop',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='crop',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='crop',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='customer',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='customer',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='equipment_mapping',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='equipment_mapping',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='equipment_mapping',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='equipment_mapping',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='equipment_vendor',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='equipment_vendor',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='equipment_vendor',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='equipment_vendor',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='farming_methods',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='farming_methods',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='farming_methods',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='farming_methods',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers_mapping',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers_mapping',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers_mapping',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='inorganic_fertilizers_mapping',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='inorganic_fertlizer_vendor',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='inorganic_fertlizer_vendor',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='inorganic_fertlizer_vendor',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='inorganic_fertlizer_vendor',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='labourer',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='labourer',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='labourer',
            name='labourer_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='labourer',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='labourer',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='land',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='land',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='land',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='land',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers_mapping',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers_mapping',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers_mapping',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='organic_fertilizers_mapping',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='organic_fertlizer_vendor',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='organic_fertlizer_vendor',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='organic_fertlizer_vendor',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='organic_fertlizer_vendor',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='pesticides',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='pesticides',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='pesticides',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='pesticides',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='pesticides_mapping',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='pesticides_mapping',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='pesticides_mapping',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='pesticides_mapping',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='pesticides_vendor',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='pesticides_vendor',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='pesticides_vendor',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='pesticides_vendor',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='season',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='season',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='season',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='season',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='season_mapping',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='season_mapping',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='season_mapping',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='season_mapping',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='seed',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='seed',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='seed',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='seed',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='seeds_mapping',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='seeds_mapping',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='seeds_mapping',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='seeds_mapping',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='seeds_vendor',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='seeds_vendor',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='seeds_vendor',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='seeds_vendor',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='added_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time'),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='soil_test',
            name='updated_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time'),
        ),
    ]
