# Generated by Django 4.0.5 on 2022-06-09 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0010_crop_added_by_crop_added_date_time_crop_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential_Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Market Name')),
                ('market_type', models.CharField(choices=[('Pr', 'Primary Market'), ('Se', 'Secondary Market'), ('Te', 'Terminal Market'), ('Re', 'Regulated Market'), ('Co', 'Co-Operative Markets'), ('St', 'State Trading')], default='Pr', max_length=2, verbose_name='Type of Market')),
                ('market_village', models.CharField(blank=True, max_length=50, null=True, verbose_name='Village')),
                ('market_taluk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Taluk')),
                ('market_district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('market_pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time')),
            ],
        ),
    ]
