# Generated by Django 4.0.5 on 2022-06-09 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0011_potential_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_to', models.DateField(blank=True, null=True, verbose_name='Available To')),
                ('quantity_Available', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity Available')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time')),
                ('mapping_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.seeds_mapping', verbose_name='Mapping Name')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticides_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_to', models.DateField(blank=True, null=True, verbose_name='Available To')),
                ('quantity_Available', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity Available')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time')),
                ('mapping_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.pesticides_mapping', verbose_name='Mapping Name')),
            ],
        ),
        migrations.CreateModel(
            name='Organic_Fertilizers_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_to', models.DateField(blank=True, null=True, verbose_name='Available To')),
                ('quantity_Available', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity Available')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time')),
                ('mapping_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.organic_fertilizers_mapping', verbose_name='Mapping Name')),
            ],
        ),
        migrations.CreateModel(
            name='Inorganic_Fertilizers_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_to', models.DateField(blank=True, null=True, verbose_name='Available To')),
                ('quantity_Available', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity Available')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time')),
                ('mapping_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.inorganic_fertilizers_mapping', verbose_name='Mapping Name')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='Available From')),
                ('available_to', models.DateField(blank=True, null=True, verbose_name='Available To')),
                ('quantity_Available', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity Available')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('added_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added Date/Time')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='Updated By')),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date/Time')),
                ('mapping_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rmapp.equipment_mapping', verbose_name='Mapping Name')),
            ],
        ),
    ]
