# Generated by Django 4.0.5 on 2022-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0012_seeds_available_pesticides_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment_vendor',
            name='equipment_name',
        ),
        migrations.RemoveField(
            model_name='inorganic_fertlizer_vendor',
            name='fertilizer_name',
        ),
        migrations.RemoveField(
            model_name='organic_fertlizer_vendor',
            name='fertilizer_name',
        ),
        migrations.RemoveField(
            model_name='pesticides_vendor',
            name='pesticides_name',
        ),
        migrations.RemoveField(
            model_name='seeds_vendor',
            name='seed_name',
        ),
    ]
