# Generated by Django 4.0.5 on 2022-11-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0013_remove_equipment_vendor_equipment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email_id'),
        ),
    ]
