# Generated by Django 4.0.5 on 2022-11-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmapp', '0014_alter_appuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='Email',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email_id'),
        ),
    ]
